#!/usr/bin/env bash
#Script that Installs nginx web server on a new machine
#the ngnix default index file contains the string "Hello World!
apt-get -y update
apt-get -y install nginx
#echo creates the files in the nginx 'html' dir and adds content to it,
#so i can specify directives to the files
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
#redirects the page '/redirect_me' to the root page '/' in nginx default server
sed -i '/server_name _;/a\\n\trewrite ^/redirect_me / permanent;' /etc/nginx/sites-available/default
#error_page directive is used with error 404 and specified to dispaly on custom_404.html page.
#When a 404 error occurs,the custom_404.html page is served by default along with it's content i echoed above.
sed -i '/server_name _;/a\\n\terror_page 404 /custom_404.html' /etc/nginx/sites-available/default
service nginx start
