#!/usr/bin/env bash
#Installs and Configures a new Ubuntu server with a HAproxy load-balancer

apt-get -y update
apt-get -y install haproxy

cp -a /etc/haproxy/haproxy.cfg{,.original_copy}
cat << EOF >> /etc/haproxy/haproxy.cfg
 
frontend mistura_frontend
         bind :80
         default_backend mistura_backend

 backend mistura_backend
         balance roundrobin
         server 152432-web-01 3.90.81.72:80 check
         server 152432-web-02 3.85.148.246:80 check
 EOF

echo "Enabled=1" >> /etc/default/haproxy
 service haproxy start