#!/usr/bin/env bash
# Installs and configures updated haproxy load balancer on a new ubuntu version 20.04
apt install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.4 -y
apt install haproxy=2.4.\*
apt update && apt upgrade -y


cp -a /etc/haproxy/haproxy.cfg{,.orig}
cat << EOF >> /etc/haproxy/haproxy.cfg

frontend mistura_frontend
         bind :80
         default_backend mistura_ALX_servers

backend mistura_backend
         balance roundrobin
         server 152432-web-01 3.90.81.72:80 check
         server 152432-web-02 3.85.148.246:80 check
EOF

echo "Enabled=1" >> /etc/default/haproxy
service haproxy start
