#!/usr/bin/env bash
#  Bash script that terminates "7-highlander" process. Without
#+ using "kill" or "killall"
# Sends a kill(Terminate .i.e SIGTERM) signal to the "trap"
#+ in 7-highlander file

pkill "./7-highlander" -f
