#!/usr/bin/env bash
# Bash script that displays:
# 1. The content of the current directory
# 2. In a list format
# 3. Where only the part of the name after the first dash is displayed
#+ e.g instead of displaying "8-for_ls", you display "for_ls".
# The "-f2" option is used to specify the number of char to remove after delim

list=$(ls)

for files in $list
do
  echo "$files" | cut -d '-' -f2
done
