#!/usr/bin/env bash
# script that gives you information about the "school" file.
# Your Bash script should check if the file exists and print:
# 1. if the file exists: school file exists
# 2. if the file does not exist: school file does not exist
# If the file exists, print:
# 1. if the file is empty: "school file is empty"
# 2. if the file is not empty: "school file is not empty"
# 3. if the file is a regular file: "school is a regular file"
# 4. if the file is not a regular file: (nothing)

filename=school

if [ -e "$filename" ]
then
  echo "school file exists"
  if [ ! -s "$filename" ]
  then
    echo "school file is empty"
  else
    echo "school file is not empty"
  fi

  if [ -f "$filename" ]
  then
    echo "school is a regular file"
  fi

else
  echo "school file does not exist"
fi
